os: linux
sudo: required
language: cpp
compiler:
- gcc

addons:
apt:
 packages:
  - cmake
  - cmake-data
before_install:
 - export DISPLAY="127.0.0.1:10.0"
 - pip install --user cpp-coveralls
 - sudo apt-get install libsfml-dev
script: 
 - cmake -H. -B_build -DBUILD_TESTS=ON
 - cmake --build _build
 - cd _build
 - ./tests --enable-gcov 
notifications:
    email: false 