os: linux
sudo: required
language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - sudo apt-get install libsfml-dev
  - cmake ..

jobs:
  include:
    - name: "make"
      script: 
        - make
    - name: "tests"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/tests.sh
notifications:
    email: false