os: linux
sudo: required
language: cpp

compiler:
  - gcc

script: 
     - mkdir -p build
     - cd build
     - sudo apt-get install libsfml-dev
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .. 
     - make
     - make Go_game_coverage
     - ctest
notifications:
    email: false 